aliases:
    fleeks: cd /home/marinkitagawa/.local/share/fleek
bling: high
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: false
name: Fleek Configuration
packages:
    - helix
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: x86_64
      hostname: MarinKitagawa
      os: linux
      username: marinkitagawa
unfree: true
